# PE06 Hrishikesh Vaze
### DWDM Ebook Assignment - Data Cleaning

In [2]:
#importing libraries
import numpy as np
import pandas as pd

### Combining and Merging Data

In [3]:
# creating two dataframes
df1 = pd.DataFrame({'key1': ['c', 'a', 'b', 'b', 'a', 'c', 'a', 'b'], 'data1': range(8)})
df2 = pd.DataFrame({'key2': ['a', 'b', 'c',  'd'], 'data2': range(4)})
print(df1)
print(df2)

  key1  data1
0    c      0
1    a      1
2    b      2
3    b      3
4    a      4
5    c      5
6    a      6
7    b      7
  key2  data2
0    a      0
1    b      1
2    c      2
3    d      3


In [4]:
# for merging two dataframes
pd.merge(df1, df2, left_on='key1', right_on='key2')

# Note:
# 1. left_on and right_on are the columns on which the merge is performed.
# 2. To merge column with same name we can simply give 'on' parameter with keyname.

key1  data1 key2  data2
0    c      0    c      2
1    c      5    c      2
2    a      1    a      0
3    a      4    a      0
4    a      6    a      0
5    b      2    b      1
6    b      3    b      1
7    b      7    b      1

### Types of join 
There are 4 types of join
1. Inner Join
2. Left Outer Join
3. Right Outer Join
4. Outer Join

By default, merge uses inner join
to specify the type of join, we use the following syntax
```py
pd.merge(df1, df2, how='right')
```

In [5]:
pd.merge(df1, df2, left_on='key1', right_on='key2', how='left')

key1  data1 key2  data2
0    c      0    c      2
1    a      1    a      0
2    b      2    b      1
3    b      3    b      1
4    a      4    a      0
5    c      5    c      2
6    a      6    a      0
7    b      7    b      1

If we want to use multiple key to merge, we use the following syntax
```py
pd.merge(df1, df2, on=['key1', 'key2', 'key3',...])
```


Concatenating DataFrames

In [7]:
arr = np.arange(12).reshape((3, 4))
print(f'Array: \n{arr}')
np.concatenate([arr, arr], axis=1)
print(f'Concatenated array: \n{np.concatenate([arr, arr], axis=1)}')

Array: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Concatenated array: 
[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]]


In [8]:
s1 = pd.Series([0, 1], index=['a', 'b'])
s2 = pd.Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = pd.Series([5, 6], index=['f', 'g'])
pd.concat([s1, s2, s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [9]:
pd.concat([s1, s2, s3], axis=1) # along columns

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

Above NaN indicates missing values correspoding to that index
<br>
We can use same thing for extending Dataframes too

In [12]:
df1 = pd.DataFrame(np.arange(6).reshape(3, 2), index=['a', 'b', 'c'], columns=['one', 'two'])
df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2), index=['a', 'c'], columns=['three', 'four'])
print(f'df1: \n{df1}')
print(f'df2: \n{df2}')

df1: 
   one  two
a    0    1
b    2    3
c    4    5
df2: 
   three  four
a      5     6
c      7     8


In [13]:
pd.concat([df1, df2], axis=1, keys=['level1', 'level2'])

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0