# PE06 Hrishikesh Vaze
### DWDM Ebook Assignment - Data Cleaning

In [1]:
#importing libraries
import numpy as np
import pandas as pd

### Combining and Merging Data

In [2]:
# creating two dataframes
df1 = pd.DataFrame({'key1': ['c', 'a', 'b', 'b', 'a', 'c', 'a', 'b'], 'data1': range(8)})
df2 = pd.DataFrame({'key2': ['a', 'b', 'c',  'd'], 'data2': range(4)})
print(df1)
print(df2)

  key1  data1
0    c      0
1    a      1
2    b      2
3    b      3
4    a      4
5    c      5
6    a      6
7    b      7
  key2  data2
0    a      0
1    b      1
2    c      2
3    d      3


In [3]:
# for merging two dataframes
pd.merge(df1, df2, left_on='key1', right_on='key2')

# Note:
# 1. left_on and right_on are the columns on which the merge is performed.
# 2. To merge column with same name we can simply give 'on' parameter with keyname.

key1  data1 key2  data2
0    c      0    c      2
1    c      5    c      2
2    a      1    a      0
3    a      4    a      0
4    a      6    a      0
5    b      2    b      1
6    b      3    b      1
7    b      7    b      1

### Types of join 
There are 4 types of join
1. Inner Join
2. Left Outer Join
3. Right Outer Join
4. Outer Join

By default, merge uses inner join
to specify the type of join, we use the following syntax
```py
pd.merge(df1, df2, how='right')
```

In [4]:
pd.merge(df1, df2, left_on='key1', right_on='key2', how='left')

key1  data1 key2  data2
0    c      0    c      2
1    a      1    a      0
2    b      2    b      1
3    b      3    b      1
4    a      4    a      0
5    c      5    c      2
6    a      6    a      0
7    b      7    b      1

If we want to use multiple key to merge, we use the following syntax
```py
pd.merge(df1, df2, on=['key1', 'key2', 'key3',...])
```


Concatenating DataFrames

In [5]:
arr = np.arange(12).reshape((3, 4))
print(f'Array: \n{arr}')
np.concatenate([arr, arr], axis=1)
print(f'Concatenated array: \n{np.concatenate([arr, arr], axis=1)}')

Array: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Concatenated array: 
[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]]


In [6]:
s1 = pd.Series([0, 1], index=['a', 'b'])
s2 = pd.Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = pd.Series([5, 6], index=['f', 'g'])
pd.concat([s1, s2, s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [7]:
pd.concat([s1, s2, s3], axis=1) # along columns

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

Above NaN indicates missing values correspoding to that index
<br>
We can use same thing for extending Dataframes too

In [8]:
df1 = pd.DataFrame(np.arange(6).reshape(3, 2), index=['a', 'b', 'c'], columns=['one', 'two'])
df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2), index=['a', 'c'], columns=['three', 'four'])
print(f'df1: \n{df1}')
print(f'df2: \n{df2}')

df1: 
   one  two
a    0    1
b    2    3
c    4    5
df2: 
   three  four
a      5     6
c      7     8


In [9]:
pd.concat([df1, df2], axis=1, keys=['level1', 'level2'])

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

# Reshaping

In [10]:
data = pd.DataFrame(np.arange(6).reshape((2, 3)), index=pd.Index(['Ohio', 'Colorado'], name='state'), columns=pd.Index(['one', 'two', 'three'], name='number'))
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

stack() interchanges cols to rows and vice versa

In [11]:
result = data.stack()
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int32

In [12]:
result.unstack()

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

we can pass column name as parameter with unstack

In [13]:
result.unstack('state')

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [14]:
# example of doing this with concat
s1 = pd.Series([0, 1, 2, 3], index=['a', 'b', 'c', 'd'])
s2 = pd.Series([4, 5, 6], index=['c', 'd', 'e'])
data2 = pd.concat([s1, s2], keys=['one', 'two'])
data2.unstack()

a    b    c    d    e
one  0.0  1.0  2.0  3.0  NaN
two  NaN  NaN  4.0  5.0  6.0

# Data Transformation

In [15]:
data3 = pd.DataFrame({'k1': ['one'] * 3 + ['two'] * 4, 'k2': [1, 1, 2, 3, 3, 4, 4]})
data3

k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4

In [16]:
data3.duplicated() # checks of duplication for each tuple

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [17]:
data3.drop_duplicates()

k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

In [18]:
# we can also drop duplicatees for duplicate value in certain cols
data3['v1'] = range(7)
data3.drop_duplicates(['k1', 'k2'])

k1  k2  v1
0  one   1   0
2  one   2   2
3  two   3   3
5  two   4   5

## Transformation using function and mapping

In [19]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami',  'corned beef', 'Bacon', 'pastrami', 'honey ham', 'nova lox'], 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [20]:
#consider this mapping
meat_to_animal = {
 'bacon': 'pig',
 'pulled pork': 'pig',
 'pastrami': 'cow',
 'corned beef': 'cow',
 'honey ham': 'pig',
 'nova lox': 'salmon'
}

In [21]:
data['animal'] = [meat_to_animal[food.lower()] for food in data['food']]
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

# Replacing Missing Values

In [22]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [23]:
data.replace(-999, np.nan) # this changes all values -999 to NaN

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [24]:
data.replace([-999, -1000], [np.nan, 0]) # for replacing multiple values

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

# Renaming Index (labels)

In [25]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),  index=['Ohio', 'Colorado', 'New York'], columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [26]:
data.index

Index(['Ohio', 'Colorado', 'New York'], dtype='object')

In [27]:
data.index.map(str.capitalize) # capitalise all labales

Index(['Ohio', 'Colorado', 'New york'], dtype='object')

In [28]:
data.rename(index=str.title, columns=str.capitalize) # or using rename method

One  Two  Three  Four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [29]:
data.rename(index={'Ohio': 'oohio'}, columns={'three': 'changed'})

one  two  changed  four
oohio       0    1        2     3
Colorado    4    5        6     7
New York    8    9       10    11

# Data Binning 

Continuous data is often discretized or otherwised separated into “bins” for analysis.Suppose you have data about a group of people in a study, and you want to group them into blocks

In [30]:
# take examples of age
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32] # ages
bins = [18, 25, 35, 60, 100] # bins boundary
cuts = pd.cut(ages, bins) # cuts first param as per boundary in 2nd param
cuts

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [31]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False) # exclude right most boundary

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64, left]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [32]:
data = np.random.randn(1000) # make random nparray of length 1000
cuts = pd.qcut(data, 4) # cut in 4equal 4 qurtile

In [33]:
pd.value_counts(cuts)

(-2.8089999999999997, -0.66]    250
(-0.66, -0.0258]                250
(-0.0258, 0.686]                250
(0.686, 3.164]                  250
dtype: int64

# Detecting Outliners

In [34]:
# np.random.seed(500)
data = pd.DataFrame(np.random.randn(1000, 4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.012855    -0.041877    -0.008839     0.015133
std       1.004850     1.041044     0.996215     0.988645
min      -3.256933    -3.408891    -2.929973    -2.863850
25%      -0.636839    -0.728098    -0.673460    -0.669145
50%       0.010645    -0.034750     0.002440     0.019473
75%       0.684821     0.653162     0.631272     0.708002
max       4.047325     3.237881     2.969108     3.024110

In [35]:
#finding or filtering
data[data[2] > 0]

0         1         2         3
1    0.447279  0.520941  1.176664  0.338434
6    0.670736  1.309238  1.021085 -0.824247
12   0.934875 -0.774985  0.509216 -0.523825
13  -0.149172  0.818955  0.071979 -0.016471
14  -0.034982  0.491707  0.403232 -1.204127
..        ...       ...       ...       ...
989  1.163727 -0.599428  2.217780  0.299780
990 -1.579924 -0.622682  1.364289 -0.686393
997  0.056370  1.583365  0.366701 -0.295526
998 -0.007789 -0.696680  0.661166  0.455819
999  0.865446 -0.218667  0.133010  0.113477

[502 rows x 4 columns]

# Permutation and random sampling

Permuting (randomly reordering) a Series or the rows in a DataFrame is easy to do using the numpy.random.permutation function. Calling permutation with the length of the axis you want to permute produces an array of integers indicating the new ordering:

In [36]:
data = pd.DataFrame(np.arange(5 * 4).reshape(5, 4))
sampler = np.random.permutation(5)
sampler

array([2, 4, 0, 1, 3])

In [37]:
data.take(sampler) # this will take all

0   1   2   3
2   8   9  10  11
4  16  17  18  19
0   0   1   2   3
1   4   5   6   7
3  12  13  14  15

In [38]:
# to select random
data.take(np.random.permutation(len(data))[::3])

0   1   2   3
2   8   9  10  11
3  12  13  14  15

# String Manipulation

In [39]:
val = "hrishi;"
val.replace(';', '') # replace substr ; with ''

'hrishi'

In [40]:
val.index(';') # get starting index of char or string

6

## Regular Expressions

In [41]:
import re

val = 'my name is hrishi'
regex = re.compile('m')
regex.findall(val) # returns two m , one from my and another from name

['m', 'm']

In [42]:
val = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""
email_regex = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'
regex = re.compile(email_regex, flags=re.IGNORECASE)
regex.findall(val)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [43]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com', 'Rob': 'rob@gmail.com', 'Wes': np.nan}
data = pd.Series(data)
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [44]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [45]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [46]:
data.str.findall(email_regex, flags=re.IGNORECASE)

Dave     [dave@google.com]
Steve    [steve@gmail.com]
Rob        [rob@gmail.com]
Wes                    NaN
dtype: object